### ISSUE TITLE
No builds for ARM architecture (Mac M2)

### ISSUE THREAD

**Issue by b-gehrke** [ontology-tools/py-horned-owl#13]
Currently the library is not build for ARM architecture and hence not available for use on e.g. M2 Macs.

**Comment by b-gehrke** [comment]
While there are [larger runners supporting apples silicon powered m1 chips](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) unfortunately there are no free hosted runners available yet.

**Comment by ShoGinn** [comment]
@b-gehrke I think this is not an issue anymore...

**Comment by b-gehrke** [comment]
Right, thank you.
